import { Inter } from "next/font/google";
import "./globals.css";
import styled from "styled-components";
import localFont from "next/font/local";
import { Suspense } from "react";
import LoadingSpinner from "@/components/loading/LoadingSpinner";
import NavBar from "@/components/layout/NavBar";
import Provider from "@/components/layout/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "SANTA",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Provider>
                    <NavBar />
                    {children}
                </Provider>
            </body>
        </html>
    );
}
